version: "3.3"
services:
  # Lunnem Api
  api_nginx:
    image: nginx:alpine
    container_name: innyx-api
    restart: unless-stopped
    tty: true
    working_dir: /var/www/html/
    volumes:
      - ./nginx/nginx-back.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "81:80"
    networks:
      - innyx_network
  backend:
    build: .
    container_name: innyx-backend
    restart: unless-stopped
    working_dir: /var/www/html/
    volumes:
      - ./backend:/var/www/html/
    ports:
      - 9000
    networks:
      - innyx_network
  portal:
    image: nginx:alpine
    container_name: innyx-portal
    restart: unless-stopped
    tty: true
    working_dir: /var/www/html/
    volumes:
      - ./portal:/var/www/html/
      - ./nginx/nginx-front.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    networks:
      - innyx_network
networks:
  innyx_network:
    driver: bridge
